#!/bin/sh

module="secvault"
device_ctl="sv_ctl"
device_data="sv_data"
mode="664"
dir="/tmp"
major=231

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
/sbin/insmod ./$module.ko $* || exit 1


# Remove stale nodes and replace them, then give gid and perms

rm -f ${dir}/${device_ctl} ${device_data}[0-3]
mknod ${dir}/${device_ctl} c $major 0
mknod ${dir}/${device_data}0 c $major 1
mknod ${dir}/${device_data}1 c $major 2
mknod ${dir}/${device_data}2 c $major 3
mknod ${dir}/${device_data}3 c $major 4
chgrp $group ${dir}/${device_data}[0-3] ${dir}/${device_ctl}
chmod $mode  ${dir}/${device_data}[0-3] ${dir}/${device_ctl}
