#!/bin/sh
module="secvault"
device_ctl="sv_ctl"
device_data="sv_data"

# invoke rmmod with all arguments we got
/sbin/rmmod $module $* || exit 1

# Remove stale nodes

rm -f /dev/${device_ctl} /dev/${device_data}[0-3]